### ISSUE TITLE
SimpleX service won't start : smp-server.ini does not exist

### ISSUE THREAD

**Issue by pp-r** [YunoHost-Apps/simplex_ynh#15]
### Describe the bug

*SimpleX service won't start because smp-server.ini does not exist. Same issue after reboot.*

### Context

- Hardware: 64 bits ARM board*
- YunoHost version: 11.1.21.4
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain:
- Using an exotic ssh port

### Steps to reproduce

- Upgrade from version 5.0.0 to 5.1.0 from the webadmin on an 64 bits ARM board.

### Expected behavior

*smp-server.ini should exist in /etc/opt/simplex/*

### Logs

https://paste.yunohost.org/xayeqofeva

**Comment by ericgaspar** [comment]
is this still an issue?

**Comment by pp-r** [comment]
It's about 1 year ago and i haven't got anymore this issue.

**Comment by pp-r** [comment]
Old issue
