### ISSUE TITLE
Arm build 5.2.0

### ISSUE THREAD

**Issue by skyuk3000** [YunoHost-Apps/simplex_ynh#17]
### Describe the bug

Update arm version to 5.2.0, have complied a new arm binary for simplex

### Context

- Hardware: Other ARM board
- YunoHost version: 11.1.21.4
- I have access to my server: Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No

### Steps to reproduce
- Upgrade from version 5.1.0 to 5.2.0 from the webadmin on an 64 bits ARM board. You can get the binary from my fork. https://github.com/skyuk3000/simplex_ynh/releases/tag/5.2.0

### Expected behaviour
- Successfully installation

### Logs
- https://paste.yunohost.org/raw/elohojejis

**Comment by ericgaspar** [comment]
#18 thanks!
