### ISSUE TITLE
Install failed on ARM64

### ISSUE THREAD

**Issue by pobee24** [YunoHost-Apps/simplex_ynh#3]
### Describe the bug

*Can't install Simplex on RPi400*

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 11.0.11
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: stable / simplex 4.1.0~ynh1

### Steps to reproduce

- *from the CLI, or the webadmin, i have the same issue when trying to install.*

### Logs

https://paste.yunohost.org/raw/xubeyagula

**Comment by tituspijean** [comment]
It looks like the provided binary is not compatible with ARM64 systems. Do you confirm this @ericgaspar?

**Comment by ericgaspar** [comment]
the binary was built on an amd64 system; therefore not compatible with arm64. (I don't have an arm64 arch to build on)

**Comment by pobee24** [comment]
hello @ericgaspar ,  how could I help you to compile on arm64 ? knowing that I know nothing about programming. 
Give you access to a Yuno instance ?

**Comment by link-leocorde** [comment]
I, too, would like to know how I could help bring arm64 into the light. (Not a programmer.)

**Comment by ericgaspar** [comment]
ARM64 version is now available for testing
`sudo yunohost app install https://github.com/YunoHost-Apps/simplex_ynh/tree/arm`

**Comment by pobee24** [comment]
Hello @ericgaspar , install since your message, and it still works

**Comment by ericgaspar** [comment]
@skyuk3000, is there any chance to get ARM64 binary updated?
