### ISSUE TITLE
Unable to install simplex: An error occurred inside the app installation script

### ISSUE THREAD

**Issue by link-leocorde** [YunoHost-Apps/simplex_ynh#4]
### Describe the bug

**Unable to install simplex: An error occurred inside the app installation script**

### Context

- Hardware: **Raspberry Pi**
- YunoHost version: **11.1.7**
- I have access to my server: **Through SSH and through the webadmin**
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: **no**
- Using, or trying to install package version/branch: **4.1.0~ynh1**

### Steps to reproduce

**Install via the webadmin via the app catalog,**
```sh
sudo yunohost app install https://github.com/YunoHost-Apps/simplex_ynh
```

### Expected behavior

**Installation of the app.**

### Logs

https://paste.yunohost.org/raw/xoqarebehi

**Comment by ericgaspar** [comment]
there is no available ARM arch binary for this app yet.

**Comment by link-leocorde** [comment]
> there is no available ARM arch binary for this app yet.

Is there an ETA or is there some way I can help support development?

**Comment by link-leocorde** [comment]
Ah, understood. And it looks like it updated and I was able to get it running today. Thanks! You can close this if you want.
