### ISSUE TITLE
ERROR - Unable to install simplex: An error occurred inside the app installation script

### ISSUE THREAD

**Issue by bee0tester-arch** [YunoHost-Apps/simplex_ynh#44]
Hi, cannot install app
--
WARNING - Invalid argument `<head><title>301'
DEBUG - 
WARNING - Usage: smp-server [-v|--version] COMMAND
DEBUG - + ynh_exit_properly
DEBUG - + [[ install =~ ^install$|^upgrade$|^restore$ ]]
ERROR - Unable to install simplex: An error occurred inside the app installation script
--
maybe this is "mistake" in install script "curl -s ip.yunohost.org"
my work test is "curl -s -L ip.yunohost.org"

### Logs 
https://paste.yunohost.org/raw/ifejeyomid

**Comment by ericgaspar** [comment]
This should be fixed with e06e9cf406e4f2a08c2e7ab84a77f71295e31060
